name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12
          - 14
          - 16
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test
      - name: Lint once
        run: npm run lint
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '14'
      - name: Build once
        run: npm run build
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '14'
